name: Build Image

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Project to build'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set outputs
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Build the Docker image
      run: docker build ${{ github.event.inputs.project_name }} --file ${{ github.event.inputs.project_name }}/Dockerfile --tag ${{ github.event.inputs.project_name }}:${{ steps.vars.outputs.sha_short }}
