name: Build Image

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Project to build'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set outputs
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Build the Docker image
      env:
        IMAGE_NAME: ${{ github.event.inputs.project_name }}
        IMAGE_TAG: ${{ steps.vars.outputs.sha_short }}
        PROJECT_NAME: ${{ github.event.inputs.project_name }}
      run: docker build $PROJECT_NAME --file $PROJECT_NAME/Dockerfile --tag $IMAGE_NAME:$IMAGE_TAG
    - name: dockerhublogin
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    - name: tag
      env:
        DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
        IMAGE_NAME: ${{ github.event.inputs.project_name }}
        IMAGE_TAG: ${{ steps.vars.outputs.sha_short }}
      run: docker tag $IMAGE_NAME:$IMAGE_TAG $DOCKERHUB_USER/$IMAGE_NAME:$IMAGE_TAG
    - name: push
      env:
        DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
        IMAGE_NAME: ${{ github.event.inputs.project_name }}
        IMAGE_TAG: ${{ steps.vars.outputs.sha_short }}
      run: docker push $DOCKERHUB_USER/$IMAGE_NAME:$IMAGE_TAG


